### ISSUE TITLE
Is it really non-blocking?

### ISSUE THREAD

**Issue by namiazad** [Nycto/S3cala#1]
I have fundamental problem with S3cala. You called it non-blocking S3 scala client but is it really non-blocking? You are using futures, great but using futures is not enough to be non-blocking. You can claim that S3cala is asynchronous but since you are working with input streams, the nature of java input stream is blocking. The difference is that you block A thread but not the current thread. So this client library is blocking but it is asynchronous. If you want to have pure non-blocking S3 scala client, you have to first use a non-blocking Http client such as netty or spray. You may also use Java NIO to build non-blocking IO. This is really important to recognise the difference between non-blocking and being asynchronous.

**Comment by twistedpair** [comment]
From `org.apache.http.impl.client.AutoRetryHttpClient` (v.4.5.1) at the root of request execution for the AWS S3 SDK (Java), we find the following, which doesn't look very non-blocking or async to me, but implies that this thread will be burning for the duration of the S3 request.

``` java
    @Override
    public HttpResponse execute(final HttpHost target, final HttpRequest request,
            final HttpContext context) throws IOException {
        for (int c = 1;; c++) {
            final HttpResponse response = backend.execute(target, request, context);
            try {
                if (retryStrategy.retryRequest(response, c, context)) {
                    EntityUtils.consume(response.getEntity());
                    final long nextInterval = retryStrategy.getRetryInterval();
                    try {
                        log.trace("Wait for " + nextInterval);
                        Thread.sleep(nextInterval);
                    } catch (final InterruptedException e) {
                        Thread.currentThread().interrupt();
                        throw new InterruptedIOException();
                    }
                } else {
                    return response;
                }
            } catch (final RuntimeException ex) {
                try {
                    EntityUtils.consume(response.getEntity());
                } catch (final IOException ioex) {
                    log.warn("I/O error consuming response content", ioex);
                }
                throw ex;
            }
        }
    }
```
