### ISSUE TITLE
Cant resolve repository

### ISSUE THREAD

**Issue by PedroSena** [Nycto/S3cala#2]
Hi,

I'd like to know if I'm missing something or not, my sbt file has:

resolvers += "Spikemark" at "https://spikemark.herokuapp.com/maven/roundeights" and
"com.roundeights" % "S3cala" % "0.1" as dependency, is it somehow incorrect ?

**Comment by Nycto** [comment]
It wasn't originally published. But I went ahead and pushed it:
https://spikemark.herokuapp.com/maven/roundeights/com/roundeights/s3cala_2.11/0.1/s3cala_2.11.pom

**Comment by hayd** [comment]
Should this be in the README?
